#!/usr/bin/env python

"""
Start application server on port 8080

The first command line argument will set the port to be bound. Remeber, you 
need root privvileges to bind ports below 1024.

"""

import os, sys
sys.path.append(os.path.join(os.path.dirname(__file__), 'lib', 'web'))

import web

urls = (
  '/', 'index'
)

class index:
	def GET(self):
		# TODO do a redirect to https
		return "Hello World"
		
if __name__ == "__main__": 
	app = web.application(urls, globals())
	app.run()
