#autogenerated by sqlautocode

import os, sys

sys.path.append(os.path.join(os.path.dirname(__file__), '..', 'lib', 'SQLAlchemy', 'lib'))
sys.path.append(os.path.join(os.path.dirname(__file__), '..'))


from sqlalchemy import *
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relation

#engine = create_engine('mysql+mysqldb://planoaa:planoaa@localhost/planoaa')
#DeclarativeBase = declarative_base()
#metadata = DeclarativeBase.metadata
#metadata.bind = engine

class Action(DeclarativeBase):
    __tablename__ = 'action'

    __table_args__ = {}

    #column definitions
    aid = Column('aid', INTEGER(display_width=11), primary_key=True, nullable=False)
    def = Column('def', TINYINT(display_width=1), nullable=False)
    mask = Column('mask', INTEGER(display_width=11))
    name = Column('name', VARCHAR(length=50))

    #relation definitions


class Color(DeclarativeBase):
    __tablename__ = 'color'

    __table_args__ = {}

    #column definitions
    bg = Column('bg', VARCHAR(charset=u'utf8', length=10))
    cid = Column('cid', INTEGER(display_width=11), primary_key=True, nullable=False)
    comment = Column('comment', VARCHAR(length=255))
    fg = Column('fg', VARCHAR(charset=u'utf8', length=10))

    #relation definitions


class Log(DeclarativeBase):
    __tablename__ = 'log'

    __table_args__ = {}

    #column definitions
    comment = Column('comment', TEXT())
    filename = Column('filename', VARCHAR(length=50))
    ip = Column('ip', CHAR(length=15))
    lid = Column('lid', INTEGER(display_width=11), primary_key=True, nullable=False)
    recid = Column('recid', INTEGER(display_width=11))
    recidx = Column('recidx', VARCHAR(length=20))
    recstr = Column('recstr', TEXT())
    tabname = Column('tabname', VARCHAR(length=50))
    tst = Column('tst', TIMESTAMP(), nullable=False)
    uid = Column('uid', VARCHAR(length=20))

    #relation definitions


class Module(DeclarativeBase):
    __tablename__ = 'module'

    __table_args__ = {}

    #column definitions
    action = Column('action', INTEGER(display_width=11), nullable=False)
    beschrieb = Column('beschrieb', VARCHAR(length=150))
    mid = Column('mid', INTEGER(display_width=11), primary_key=True, nullable=False)
    name = Column('name', VARCHAR(length=30))

    #relation definitions


class Note(DeclarativeBase):
    __tablename__ = 'notes'

    __table_args__ = {}

    #column definitions
    color = Column('color', CHAR(length=10))
    comment = Column('comment', TEXT())
    nid = Column('nid', INTEGER(display_width=11), primary_key=True, nullable=False)
    pid = Column('pid', INTEGER(display_width=11), nullable=False)
    ym = Column('ym', CHAR(length=6))

    #relation definitions


class Permission(DeclarativeBase):
    __tablename__ = 'permission'

    __table_args__ = {}

    #column definitions
    level = Column('level', INTEGER(display_width=11))
    mid = Column('mid', INTEGER(display_width=11))
    prid = Column('prid', INTEGER(display_width=11), primary_key=True, nullable=False)
    uid = Column('uid', INTEGER(display_width=11))

    #relation definitions


class Personal(DeclarativeBase):
    __tablename__ = 'personal'

    __table_args__ = {}

    #column definitions
    adresse = Column('adresse', VARCHAR(length=100))
    aktiv = Column('aktiv', VARCHAR(length=1))
    anrede = Column('anrede', VARCHAR(length=20))
    bemerkung1 = Column('bemerkung1', TEXT())
    bemerkung2 = Column('bemerkung2', TEXT())
    combi = Column('combi', INTEGER(display_width=10))
    email = Column('email', VARCHAR(length=50))
    f1 = Column('f1', VARCHAR(length=20))
    f10 = Column('f10', VARCHAR(length=20))
    f11 = Column('f11', VARCHAR(length=20))
    f2 = Column('f2', VARCHAR(length=20))
    f3 = Column('f3', VARCHAR(length=20))
    f4 = Column('f4', VARCHAR(length=20))
    f5 = Column('f5', VARCHAR(length=20))
    f6 = Column('f6', VARCHAR(length=20))
    f7 = Column('f7', VARCHAR(length=20))
    f8 = Column('f8', VARCHAR(length=20))
    f9 = Column('f9', VARCHAR(length=20))
    fax = Column('fax', VARCHAR(length=15))
    gebdatum = Column('gebdatum', DATE())
    kuerzel = Column('kuerzel', VARCHAR(length=20))
    name = Column('name', VARCHAR(length=40), nullable=False)
    natel = Column('natel', VARCHAR(length=15))
    notarzt = Column('notarzt', VARCHAR(length=1))
    personalid = Column('personalid', VARCHAR(length=20))
    pid = Column('pid', INTEGER(display_width=11), primary_key=True, nullable=False)
    pidp = Column('pidp', INTEGER(display_width=11), nullable=False)
    plz = Column('plz', VARCHAR(length=10))
    ptid = Column('ptid', INTEGER(display_width=11), nullable=False)
    sgnor = Column('sgnor', VARCHAR(length=1))
    tel_g = Column('tel_g', VARCHAR(length=15))
    tel_p = Column('tel_p', VARCHAR(length=15))
    titel = Column('titel', VARCHAR(length=20))
    verfuegbar = Column('verfuegbar', VARCHAR(length=1))
    vorname = Column('vorname', VARCHAR(length=30), nullable=False)
    wohnort = Column('wohnort', VARCHAR(length=30))

    #relation definitions


class Perstyp(DeclarativeBase):
    __tablename__ = 'perstyp'

    __table_args__ = {}

    #column definitions
    kurz = Column('kurz', VARCHAR(charset=u'utf8', length=4))
    lang = Column('lang', VARCHAR(charset=u'utf8', length=20))
    ptid = Column('ptid', INTEGER(display_width=11), primary_key=True, nullable=False)
    sort = Column('sort', INTEGER(display_width=10, unsigned=True))

    #relation definitions


class Rotation(DeclarativeBase):
    __tablename__ = 'rotation'

    __table_args__ = {}

    #column definitions
    bemerkung1 = Column('bemerkung1', TEXT())
    bemerkung2 = Column('bemerkung2', TEXT())
    bgrad = Column('bgrad', FLOAT())
    bgradj = Column('bgradj', TINYINT(display_width=1), nullable=False)
    cid = Column('cid', INTEGER(display_width=11))
    f1 = Column('f1', VARCHAR(length=10))
    f2 = Column('f2', VARCHAR(length=10))
    jm = Column('jm', INTEGER(display_width=11))
    kuerzel = Column('kuerzel', VARCHAR(length=10))
    meldetyp = Column('meldetyp', INTEGER(display_width=10))
    meldung = Column('meldung', INTEGER(display_width=1))
    pid = Column('pid', INTEGER(display_width=11), nullable=False)
    rbid = Column('rbid', INTEGER(display_width=10, unsigned=True), nullable=False)
    rid = Column('rid', INTEGER(display_width=11), primary_key=True, nullable=False)
    rort = Column('rort', INTEGER(display_width=11))
    rpos = Column('rpos', INTEGER(display_width=11), nullable=False)
    rtyp = Column('rtyp', VARCHAR(length=10))
    show = Column('show', VARCHAR(length=1))
    ukbb = Column('ukbb', TINYINT(display_width=1, unsigned=True))

    #relation definitions


class Rotation2person(DeclarativeBase):
    __tablename__ = 'rotation2person'

    __table_args__ = {}

    #column definitions
    pid = Column('pid', INTEGER(display_width=11), nullable=False)
    pos = Column('pos', INTEGER(display_width=11), nullable=False)
    r2pid = Column('r2pid', INTEGER(display_width=11), primary_key=True, nullable=False)
    rtid = Column('rtid', INTEGER(display_width=11), nullable=False)
    ym = Column('ym', CHAR(length=6), nullable=False)

    #relation definitions


class Rotationsort(DeclarativeBase):
    __tablename__ = 'rotationsort'

    __table_args__ = {}

    #column definitions
    anzpos = Column('anzpos', INTEGER(display_width=11))
    kuerzel = Column('kuerzel', VARCHAR(length=20))
    name = Column('name', VARCHAR(length=50))
    roid = Column('roid', INTEGER(display_width=11), primary_key=True, nullable=False)
    sort = Column('sort', INTEGER(display_width=11))

    #relation definitions


class Rotationstyp(DeclarativeBase):
    __tablename__ = 'rotationstyp'

    __table_args__ = {}

    #column definitions
    name = Column('name', VARCHAR(charset=u'utf8', length=20))
    pos = Column('pos', INTEGER(display_width=11), nullable=False)
    roid = Column('roid', INTEGER(display_width=11))
    rtid = Column('rtid', INTEGER(display_width=11), primary_key=True, nullable=False)
    sort = Column('sort', INTEGER(display_width=11))

    #relation definitions


class Rotblock(DeclarativeBase):
    __tablename__ = 'rotblock'

    __table_args__ = {}

    #column definitions
    comment = Column('comment', TEXT())
    neueintritt = Column('neueintritt', TINYINT(display_width=1), nullable=False)
    pid = Column('pid', INTEGER(display_width=10, unsigned=True))
    rbid = Column('rbid', INTEGER(display_width=10, unsigned=True), primary_key=True, nullable=False)
    rbis = Column('rbis', CHAR(length=6))
    rvon = Column('rvon', CHAR(length=6))

    #relation definitions


class Setting(DeclarativeBase):
    __tablename__ = 'setting'

    __table_args__ = {}

    #column definitions
    name = Column('name', VARCHAR(charset=u'utf8', length=50))
    sid = Column('sid', INTEGER(display_width=11), primary_key=True, nullable=False)
    uid = Column('uid', INTEGER(display_width=11))
    value = Column('value', TEXT(charset=u'utf8'))

    #relation definitions


class User(DeclarativeBase):
    __tablename__ = 'user'

    __table_args__ = {}

    #column definitions
    aktiv = Column('aktiv', TINYINT(display_width=1), nullable=False)
    kuerzel = Column('kuerzel', VARCHAR(length=10))
    login = Column('login', VARCHAR(length=20))
    name = Column('name', VARCHAR(length=50))
    profil = Column('profil', VARCHAR(length=20))
    pw = Column('pw', VARCHAR(length=20))
    tst = Column('tst', TIMESTAMP(), nullable=False)
    uid = Column('uid', INTEGER(display_width=11), primary_key=True, nullable=False)
    vorname = Column('vorname', VARCHAR(length=50))

    #relation definitions


